# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -Djava.io.tmpdir=D:/Temp

android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=35
kapt.use.worker.api=false
kapt.incremental.apt=false

android.injected.room.disableVerification=true